mapping:
  20220201163415102264_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sample_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415102278_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sample_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415102283_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sample_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Role
  20220201163415102286_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Specimen_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Process
  20220201163415102290_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Biobank_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_ID
  20220201163415102293_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Biobank_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Entity
  20220201163415102300_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Biobank_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Role
  20220201163415102303_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Specimen_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Process
  20220201163415102307_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415102310_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415102315_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Role
  20220201163415102318_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Role
  20220201163415102322_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Process
  20220201163415102325_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000659
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Process
  20220201163415102330_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Specimen_Output
  20220201163415102333_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0100051
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Specimen_Output
  20220201163415102337_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#BiobankID
  20220201163415102340_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(biobank_url)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415102343_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000947
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Role
  20220201163415102347_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Role
  20220201163415102350_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Process
  20220201163415102355_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0302893
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Process
  20220201163415102359_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient for biobank sample collection'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Role
  20220201163415102362_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Sample collection process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sample_Process
  20220201163415102366_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Specimen'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Specimen_Output
  20220201163415102369_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Biobank for sample storage'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Role
  20220201163415102372_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Sample storage process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_Process
  20220201163415102375_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415102379_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(biobank_id)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Biobank_ID
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

