---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  laboratory_measurement-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_thisPerson_thisRole:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_thisRole:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#thisRole
        type: iri
  entity_has_role_thisRole:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: https://w3id.org/biolink/vocab/Case
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/object
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#thisRole
        type: iri
  thisRole_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#thisRole
    po:
    - predicates: a
      objects:
        value: obo:OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: " Role: Patient"
        datatype: xsd:string
  thisRole_realized_some_laboratory_measuring_process:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#thisRole
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
        type: iri
  process_some_laboratory_measuring_process_process_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: a
      objects:
        value: https://w3id.org/biolink/vocab/Process
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(processURI)"
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process: $(processLabel)'
        datatype: xsd:string
  process_some_laboratory_measuring_process_process_annotation_start:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: http://semanticscience.org/resource/has-start-time
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process_startdate_date
        type: iri
  process_some_laboratory_measuring_process_process_annotation_start_value:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process_startdate_date
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/start-date
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Start Date: $(date)'
        datatype: xsd:string
  process_some_laboratory_measuring_process_process_annotation_end:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: http://semanticscience.org/resource/has-end-time
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process_enddate_date
        type: iri
  process_some_laboratory_measuring_process_process_annotation_end_value:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process_enddate_date
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/end-date
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'End Date: $(date)'
        datatype: xsd:string
  process_some_laboratory_measuring_process_has_input_material_tested:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: http://semanticscience.org/resource/has-input
      objects:
        value: this:individual_$(pid)_$(uniqid)#process_unidentifiedProcess_Output
        type: iri
  process_some_laboratory_measuring_process_has_input_material_tested_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_$(pid)_$(uniqid)#process_unidentifiedProcess_Output
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
    - predicates: a
      objects:
        value: https://w3id.org/biolink/vocab/InformationContentEntity
        type: iri
    - predicates: a
      objects:
        value: "$(material_tested)"
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process Input: $(material_tested_label) - Type: material_tested'
        datatype: xsd:string
  process_some_laboratory_measuring_process_has_target_target_entity:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: http://semanticscience.org/resource/has-target
      objects:
        value: this:individual_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Target
        type: iri
  process_some_laboratory_measuring_process_has_target_target_entity_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Target
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(target)"
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process Target: $(target_label)'
        datatype: xsd:string
  some_laboratory_measuring_process_specified_by_laboratory_measurement_process_protocol_specifictype_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Protocol: Process'
        datatype: xsd:string
  some_laboratory_measuring_process_specified_by_laboratory_measurement_process_protocol:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: http://semanticscience.org/resource/is-specified-by
      objects:
        value: "$(protocolURI)"
        type: iri
  some_laboratory_measuring_process_specified_by_laboratory_measurement_process_protocol_annotation:
    sources:
    - laboratory_measurement-source
    s: "$(protocolURI)"
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C42651
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C42651
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Protocol: $(protocolURI)'
        datatype: xsd:string
  process_some_laboratory_measuring_process_process_has_output:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)_process#process_some_laboratory_measuring_process
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
        type: iri
  process_some_laboratory_measuring_process_Output_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
    - predicates: a
      objects:
        value: https://w3id.org/biolink/vocab/InformationContentEntity
        type: iri
  process_some_laboratory_measuring_process_Output_type_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  process_some_laboratory_measuring_process_Output_type_label_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: rdfs:label
      objects:
        value: 'Output Type: measurement-value'
        datatype: xsd:string
  process_some_laboratory_measuring_process_Output_value_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(value)"
        datatype: xsd:float
  process_some_laboratory_measuring_process_Output_value_comments:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: rdfs:comment
      objects:
        value: "$(comments)"
        datatype: xsd:string
  process_some_laboratory_measuring_process_Output_hasunit_unit:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: http://semanticscience.org/resource/has-unit
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output_unit
        type: iri
  process_some_laboratory_measuring_process_Output_unit_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output_unit
    po:
    - predicates: rdf:type
      objects:
        value: "$(unitURI)"
        type: iri
  process_some_laboratory_measuring_process_Output_unit_label_annotation:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output_unit
    po:
    - predicates: rdfs:label
      objects:
        value: "$(unitLabel)"
        datatype: xsd:string
  inout_from_process_some_laboratory_measuring_process_refers_to_concepts:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_some_laboratory_measuring_process_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#measured_attribute_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_process_some_laboratory_measuring_process:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#measured_attribute_TypedAttributeNode
        type: iri
  inout_from_process_some_laboratory_measuring_process_refers_to_concept_measured_attribute_type:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#measured_attribute_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: http://quality.ontology.org/some_attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_000614
        type: iri
    - predicates: rdf:type
      objects:
        value: https://w3id.org/biolink/vocab/Attribute
        type: iri
  inout_from_process_some_laboratory_measuring_process_refers_to_concept_measured_attribute_label:
    sources:
    - laboratory_measurement-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#measured_attribute_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: 'Attribute Type: Some laboratory measured attribute'
        datatype: xsd:string
