mapping:
  20220529211110118509_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Care_pathway_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220529211110118535_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Care_pathway_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220529211110118544_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Care_pathway_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: First contact patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Care_pathway_Role
  20220529211110118552_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Care_pathway_Startdate
      predicate: sio:SIO_000680
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Care_pathway_Enddate
      predicate: sio:SIO_000681
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C16205
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C159705
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: First contact with specialized center'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Care_pathway_Process
  20220529211110118558_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(first_contact_date)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(first_contact_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Care_pathway_Startdate
  20220529211110118563_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(first_contact_date)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(first_contact_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Care_pathway_Enddate
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

