mapping:
  20220201163415388772_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415388786_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415388791_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220201163415388795_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388799_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388802_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388808_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388811_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415388815_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415388818_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220201163415388822_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220201163415388827_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388831_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(test_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388834_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C107391
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Startdate
  20220201163415388839_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Enddate
  20220201163415388842_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Output
  20220201163415388846_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Input
  20220201163415388849_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C17048
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Input
  20220201163415388853_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220201163415388856_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: $(test_name)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220201163415388859_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(test_date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Startdate
  20220201163415388864_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(test_date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Enddate
  20220201163415388868_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Disability score'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Output
  20220201163415388871_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: Questionnaire'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Input
  20220201163415388875_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415388878_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(test_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)##Disability_Startdate
  20220201163415388881_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(test_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Enddate
  20220201163415388884_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(score)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

