mapping:
  20220215150750382794_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220215150750382808_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220215150750382812_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220215150750382816_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382820_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382823_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382829_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Disability_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382832_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220215150750382836_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220215150750382839_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220215150750382845_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220215150750382849_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382852_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(test_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382855_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C107391
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Startdate
  20220215150750382860_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Enddate
  20220215150750382863_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Output
  20220215150750382867_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Input
  20220215150750382870_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C17048
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Input
  20220215150750382874_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Role
  20220215150750382877_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: $(test_name)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Process
  20220215150750382881_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(test_date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Startdate
  20220215150750382885_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(test_date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Enddate
  20220215150750382889_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Disability score'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Output
  20220215150750382892_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: Questionnaire'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Input
  20220215150750382896_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220215150750382899_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(test_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)##Disability_Startdate
  20220215150750382902_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(test_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Enddate
  20220215150750382905_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(score)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Disability_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

