mapping:
  20220216115112200162_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Symptom_onset_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112200177_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Symptom_onset_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112200182_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Symptom_onset_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112200186_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Symptom_onset_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Role
  20220216115112200189_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Symptom_onset_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Process
  20220216115112200196_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Symptom_onset_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Output
  20220216115112200200_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Diagnosis_date_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112200203_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Diagnosis_date_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112200207_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Diagnosis_date_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112200210_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Diagnosis_date_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Role
  20220216115112200214_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Diagnosis_date_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Process
  20220216115112200217_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Diagnosis_date_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Output
  20220216115112200221_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112200225_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112200229_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Role
  20220216115112200234_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Role
  20220216115112200238_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Process
  20220216115112200242_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001052
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Process
  20220216115112200246_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Output
  20220216115112200249_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(onset_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Output
  20220216115112200252_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Attribute
  20220216115112200257_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C25279
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Attribute
  20220216115112200261_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Role
  20220216115112200264_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Role
  20220216115112200267_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Process
  20220216115112200271_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001052
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Process
  20220216115112200275_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Output
  20220216115112200279_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(diagnosis_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Output
  20220216115112200282_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Attribute
  20220216115112200286_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C156420
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Attribute
  20220216115112200290_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Symptom onset patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Role
  20220216115112200293_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Symptom onset date recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Process
  20220216115112200296_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Date of onset'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Output
  20220216115112200299_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Stage or date of onset)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Attribute
  20220216115112200303_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Diagnosis date patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Role
  20220216115112200306_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Diagnosis date recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Process
  20220216115112200311_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Age at diagnosis'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Output
  20220216115112200314_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Stage or date of diagnosis'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Attribute
  20220216115112200317_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112200320_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(onset_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Symptom_onset_Output
  20220216115112200324_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(diagnosis_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Diagnosis_date_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

