mapping:
  20220603101455262039_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Symptom_onset_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Diagnosis_date_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220603101455262056_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Symptom_onset_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Symptom_onset_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Diagnosis_date_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Diagnosis_date_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220603101455262064_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Symptom_onset_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: Symptom onset patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Symptom_onset_Role
  20220603101455262070_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Symptom_onset_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001052
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Symptom onset date recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Symptom_onset_Process
  20220603101455262075_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Symptom_onset_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(onset_uri)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: Date of onset'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(onset_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Symptom_onset_Output
  20220603101455262082_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Diagnosis_date_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: Diagnosis date patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Diagnosis_date_Role
  20220603101455262087_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Diagnosis_date_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001052
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Diagnosis date recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Diagnosis_date_Process
  20220603101455262093_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Diagnosis_date_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(diagnosis_uri)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: Age at diagnosis'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(diagnosis_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Diagnosis_date_Output
  20220603101455262098_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C25279
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Stage or date of onset'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Symptom_onset_Attribute
  20220603101455262102_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C156420
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Stage or date of diagnosis'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Diagnosis_date_Attribute
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

