mapping:
  20220216115112777132_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Genetic_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112777147_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Genetic_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112777152_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#HGVS_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112777156_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(omim_uri)
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112777161_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112777166_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#HGVS_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Genetic_Role
  20220216115112777170_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#OMIM_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Genetic_Role
  20220216115112777173_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#HGNC_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Genetic_Role
  20220216115112777177_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#HGVS_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Process
  20220216115112777180_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#HGVS_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Output
  20220216115112777184_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#OMIM_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Process
  20220216115112777188_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(omim_uri)
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Output
  20220216115112777192_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#HGNC_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Process
  20220216115112777197_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Output
  20220216115112777202_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112777206_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115112777210_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Genetic_Role
  20220216115112777213_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Genetic_Role
  20220216115112777217_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C15709
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Process
  20220216115112777221_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Process
  20220216115112777224_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Output
  20220216115112777229_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001388
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Output
  20220216115112777232_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Attribute
  20220216115112777236_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Attribute
  20220216115112777240_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C171178
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Attribute
  20220216115112777244_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C15709
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Process
  20220216115112777248_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Process
  20220216115112777251_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Output
  20220216115112777255_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001381
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Output
  20220216115112777259_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(omim_uri)
  20220216115112777263_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(omim_uri)
  20220216115112777266_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: edam:data_1153
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(omim_uri)
  20220216115112777270_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C15709
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Process
  20220216115112777273_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Process
  20220216115112777277_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Output
  20220216115112777281_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001381
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Output
  20220216115112777286_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220216115112777289_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220216115112777293_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: edam:data_2298
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220216115112777296_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Genetic diagnosis patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Genetic_Role
  20220216115112777300_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: HGVS genetic testing'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Process
  20220216115112777303_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: HGVS measurement value'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Output
  20220216115112777307_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hgvs_string)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Attribute
  20220216115112777310_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: OMIM genetic testing'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Process
  20220216115112777315_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: OMIM genome sequence variant'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Output
  20220216115112777318_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(omim_uri)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(omim_uri)
  20220216115112777322_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: HGNC genetic testing'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Process
  20220216115112777326_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: HGNC genome sequence variant'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Output
  20220216115112777329_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(clinvar_uri)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220216115112777332_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115112777336_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(hgvs_string)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGVS_Output
  20220216115112777339_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(omim_uri)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#OMIM_Output
  20220216115112777343_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(clinvar_uri)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#HGNC_Output
prefixes:
  edam: http://edamontology.org/
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

