mapping:
  20220529211126310467_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Genetic_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220529211126310493_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Genetic_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: $(omim_uri)
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: $(hgnc_uri)
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220529211126310503_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_HGVS_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_OMIM_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_HGNC_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: Genetic diagnosis patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genetic_Role
  20220529211126310509_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_HGVS_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: obo:NCIT_C15709
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: HGVS genetic testing'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_HGVS_Process
  20220529211126310516_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001388
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: HGVS measurement value'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(hgvs_string)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_HGVS_Output
  20220529211126310522_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_OMIM_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: obo:NCIT_C15709
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: OMIM genetic testing'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_OMIM_Process
  20220529211126310529_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(omim_uri)
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001381
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: OMIM genome sequence variant'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(omim_uri)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_OMIM_Output
  20220529211126310535_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_HGNC_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: obo:NCIT_C15709
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: HGNC genetic testing'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_HGNC_Process
  20220529211126310541_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(hgnc_uri)
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001381
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: HGNC genome sequence variant'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(hgnc_uri)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_HGNC_Output
  20220529211126310547_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C171178
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hgvs_string)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220529211126310553_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: edam:data_1153
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(omim_uri)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(omim_uri)
  20220529211126310560_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: edam:data_2298
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hgnc_uri)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(hgnc_uri)
prefixes:
  edam: http://edamontology.org/
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

