mapping:
  20220216165603917180_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216165603917195_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216165603917199_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216165603917203_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220216165603917207_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917212_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917216_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917219_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917225_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Target
      predicate: sio:SIO_000291
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917229_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(protocolURI)
      predicate: sio:SIO_000339
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917233_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220216165603917237_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Unit
      predicate: sio:SIO_000221
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220216165603917240_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216165603917244_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216165603917248_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220216165603917251_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220216165603917255_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917258_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(processURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917263_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220216165603917266_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220216165603917269_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220216165603917274_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220216165603917278_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(material_tested)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220216165603917281_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220216165603917285_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(target)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220216165603917288_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220216165603917291_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C42651
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220216165603917295_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(unitURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Unit
  20220216165603917298_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
  20220216165603917303_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:Case
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216165603917307_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:Procedure
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917310_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:InformationContentEntity
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220216165603917314_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:InformationContentEntity
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220216165603917317_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:Attribute
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
  20220216165603917320_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220216165603917324_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: $(processLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220216165603917328_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220216165603917331_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220216165603917335_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Measurement value'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220216165603917339_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(comments)
      predicate: rdfs:comment
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220216165603917342_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: $(material_tested_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220216165603917345_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Target type: $(target_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220216165603917349_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Protocol: $(protocolLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220216165603917352_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Target type: $(unitLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Unit
  20220216165603917357_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: Lab measurement attribute
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
  20220216165603917360_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216165603917363_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220216165603917366_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220216165603917370_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:float
        value: $(value)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
prefixes:
  biolink: https://w3id.org/biolink/vocab/
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

