mapping:
  20220201163415673545_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415673559_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415673566_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415673570_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220201163415673573_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673577_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673582_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673585_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673589_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Target
      predicate: sio:SIO_000291
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673592_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(protocolURI)
      predicate: sio:SIO_000339
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673596_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220201163415673599_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Unit
      predicate: sio:SIO_000221
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220201163415673603_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415673608_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163415673613_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220201163415673617_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220201163415673620_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673624_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(processURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673627_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C107391
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220201163415673630_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220201163415673634_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220201163415673639_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220201163415673643_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(material_tested)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220201163415673648_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220201163415673651_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(target)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220201163415673655_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220201163415673658_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C42651
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220201163415673661_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(unitURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Unit
  20220201163415673665_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220201163415673668_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: $(processLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220201163415673673_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220201163415673676_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220201163415673679_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Measurement value'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220201163415673682_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(comments)
      predicate: rdfs:comment
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220201163415673687_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: $(material_tested_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220201163415673690_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Target type: $(target_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220201163415673693_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Protocol: $(protocolLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220201163415673697_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Target type: $(unitLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Unit
  20220201163415673701_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163415673704_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)##Lab_measurement_Startdate
  20220201163415673707_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220201163415673711_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:float
        value: $(value)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

