mapping:
  20220202164450524396_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220202164450524411_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220202164450524416_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220202164450524419_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220202164450524423_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524429_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524433_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524436_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524440_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Target
      predicate: sio:SIO_000291
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524444_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(protocolURI)
      predicate: sio:SIO_000339
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524448_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220202164450524453_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Lab_measurement_Unit
      predicate: sio:SIO_000221
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220202164450524456_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220202164450524460_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220202164450524464_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220202164450524467_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220202164450524471_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524474_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(processURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524478_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C107391
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220202164450524482_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220202164450524486_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220202164450524490_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220202164450524494_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(material_tested)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220202164450524497_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220202164450524501_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(target)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220202164450524504_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220202164450524507_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C42651
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220202164450524511_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(unitURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Unit
  20220202164450524514_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:Case
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220202164450524518_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:Procedure
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524523_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:InformationContentEntity
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220202164450524526_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:InformationContentEntity
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220202164450524530_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:Attribute
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Attribute
  20220202164450524533_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Role
  20220202164450524536_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: $(processLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Process
  20220202164450524540_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220202164450524544_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220202164450524547_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Measurement value'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220202164450524551_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(comments)
      predicate: rdfs:comment
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
  20220202164450524554_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: $(material_tested_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Input
  20220202164450524558_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Target type: $(target_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Target
  20220202164450524561_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Protocol: $(protocolLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(protocolURI)
  20220202164450524564_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Target type: $(unitLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Unit
  20220202164450524568_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220202164450524572_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Startdate
  20220202164450524576_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Enddate
  20220202164450524579_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:float
        value: $(value)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Lab_measurement_Output
prefixes:
  biolink: https://w3id.org/biolink/vocab/
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

