mapping:
  20220201163414814490_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163414814504_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163414814509_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163414814513_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Role
  20220201163414814516_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814522_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814526_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814530_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814534_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Consent_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Output
  20220201163414814537_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163414814541_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163414814545_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Role
  20220201163414814548_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Role
  20220201163414814553_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814557_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000810
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814560_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Startdate
  20220201163414814564_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Enddate
  20220201163414814567_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Output
  20220201163414814572_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Input
  20220201163414814575_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:ICO_0000001
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Input
  20220201163414814579_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Attribute
  20220201163414814583_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(result_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Attribute
  20220201163414814587_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient for status recording'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Role
  20220201163414814591_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Consenting'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Process
  20220201163414814594_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Startdate
  20220201163414814597_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Enddate
  20220201163414814601_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Patient consent record'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Output
  20220201163414814605_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: Consent document'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Input
  20220201163414814609_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(result_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Attribute
  20220201163414814613_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163414814616_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)##Consent_Startdate
  20220201163414814619_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Enddate
  20220201163414814623_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(result_label)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Output
  20220201163414814626_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(consent_template)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Consent_Input
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

