mapping:
  20220201163413091754_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Status_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163413091770_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Status_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163413091774_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Status_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163413091778_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Status_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Role
  20220201163413091782_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Status_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Process
  20220201163413091788_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Status_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Output
  20220201163413091792_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Death_information_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163413091797_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Death_information_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Role
  20220201163413091801_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Death_information_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Process
  20220201163413091804_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Death_information_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Output
  20220201163413091808_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163413091812_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220201163413091816_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Role
  20220201163413091821_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Role
  20220201163413091824_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001052
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Process
  20220201163413091828_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Process
  20220201163413091832_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Output
  20220201163413091837_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Attribute
  20220201163413091841_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(status_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Attribute
  20220201163413091845_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Process
  20220201163413091848_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Output
  20220201163413091853_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Attribute
  20220201163413091857_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C70810
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Attribute
  20220201163413091861_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient for status recording'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Role
  20220201163413091864_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Status recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Process
  20220201163413091868_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: $(status_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Output
  20220201163413091871_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(status_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Attribute
  20220201163413091875_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Death information recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Process
  20220201163413091879_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Patient death information)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Output
  20220201163413091884_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Date of death'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Attribute
  20220201163413091888_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220201163413091891_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Status_Output
  20220201163413091895_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(death_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Death_information_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

