mapping:
  20220529211104252354_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220529211104252382_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Death_information_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220529211104252391_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Death_information_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: Patient for status recording'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Status_Role
  20220529211104252400_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Startdate
      predicate: sio:SIO_000680
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Enddate
      predicate: sio:SIO_000681
    - objects:
        type: iri
        value: sio:SIO_001052
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Status recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Status_Process
  20220529211104252406_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Status_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: $(status_label)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(status_label)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Status_Output
  20220529211104252412_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Death_information_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Death information recording process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Death_information_Process
  20220529211104252418_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Death_information_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: Patient death information'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(death_date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Death_information_Output
  20220529211104252425_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C166244
      predicate: rdf:type
    - objects:
        type: iri
        value: $(status_uri)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(status_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Status_Attribute
  20220529211104252430_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Status_Startdate
  20220529211104252436_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Status_Enddate
  20220529211104252442_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C70810
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Date of death'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Death_information_Attribute
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

