mapping:
  20220216115111339622_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Birthdate_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115111339636_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Birthdate_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115111339641_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Birthdate_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115111339645_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Birthdate_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Role
  20220216115111339648_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Birthdate_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Process
  20220216115111339654_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Birthdate_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Output
  20220216115111339659_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sex_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115111339663_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sex_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115111339667_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sex_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115111339670_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sex_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Role
  20220216115111339673_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sex_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Process
  20220216115111339677_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)#Sex_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Output
  20220216115111339680_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115111339685_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Entity
  20220216115111339688_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Role
  20220216115111339692_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Role
  20220216115111339696_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Process
  20220216115111339700_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Output
  20220216115111339703_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Attribute
  20220216115111339706_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C68615
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Attribute
  20220216115111339710_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Role
  20220216115111339714_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Role
  20220216115111339718_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Process
  20220216115111339721_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Output
  20220216115111339725_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Attribute
  20220216115111339728_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(sexURI)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Attribute
  20220216115111339731_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C28421
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Attribute
  20220216115111339741_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient for age assessment'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Role
  20220216115111339745_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: age measuring process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Process
  20220216115111339749_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Birth date'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Output
  20220216115111339753_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Birth date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Attribute
  20220216115111339756_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Patient for gender assessment'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Role
  20220216115111339759_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: sex measuring process'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Process
  20220216115111339763_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: $(sexLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Output
  20220216115111339766_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(sexLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Sex_Attribute
  20220216115111339769_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#ID
  20220216115111339773_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(birthdate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Output
  20220216115111339777_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(sexLabel)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)#Birthdate_Output
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

