mapping:
  20220531122124289776_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:#ID
      predicate: biolink:hasID
    - objects:
        type: iri
        value: biolink:Case
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(uniqid)#Entity
  20220531122124289794_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: biolink:ID
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: biolink:hasnumerical_value
    sources:
    - source_cde_test
    subjects: this:$(uniqid)#ID
prefixes:
  biolink: https://w3id.org/biolink/vocab/
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

