mapping:
  20220529211137917340_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220529211137917367_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Phenotype_Attribute
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000008
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220529211137917375_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: Undiagnosed patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Role
  20220529211137917383_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Startdate
      predicate: sio:SIO_000680
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Enddate
      predicate: sio:SIO_000681
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Phenotype_Input
      predicate: sio:SIO_000230
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Genotype_Input
      predicate: sio:SIO_000230
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001001
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Medical diagnosis'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220529211137917389_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Output type: Undiagnosed label'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: Undiagnosed
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Output
  20220529211137917396_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Phenotype_Attribute
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C102741
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Input type: HP_Phenotype'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(hp_label)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Input
  20220529211137917402_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: sio:SIO_001388
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Input type: HGVS_Genotype'
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(hgvs_string)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genotype_Input
  20220529211137917408_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Startdate
  20220529211137917413_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Enddate
  20220529211137917419_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C113725
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Undiagnosed'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
  20220529211137917424_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: $(hp_uri)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hp_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Attribute
  20220529211137917430_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C171178
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hgvs_string)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

