mapping:
  20220404183301349813_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Role
      predicate: sio:SIO_000020
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220404183301349828_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Role
      predicate: sio:SIO_000228
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220404183301349833_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220404183301349837_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Phenotype_Attribute
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220404183301349840_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000008
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220404183301349845_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Process
      predicate: sio:SIO_000356
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Role
  20220404183301349855_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Startdate
      predicate: sio:SIO_000680
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349858_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Enddate
      predicate: sio:SIO_000681
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349862_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Output
      predicate: sio:SIO_000229
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349865_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Phenotype_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349869_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Genotype_Input
      predicate: sio:SIO_000230
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349872_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Output
  20220404183301349876_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Phenotype_Attribute
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Input
  20220404183301349880_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(clinvar_uri)
      predicate: sio:SIO_000628
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genotype_Input
  20220404183301349884_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220404183301349887_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220404183301349892_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Role
  20220404183301349896_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Role
  20220404183301349900_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000006
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349903_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001001
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349907_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Startdate
  20220404183301349911_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Enddate
  20220404183301349915_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Output
  20220404183301349919_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
  20220404183301349922_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C113725
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
  20220404183301349925_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Input
  20220404183301349929_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Attribute
  20220404183301349933_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(hp_uri)
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Attribute
  20220404183301349938_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genotype_Input
  20220404183301349941_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_001388
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genotype_Input
  20220404183301349945_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000614
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220404183301349948_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: obo:NCIT_C171178
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220404183301349951_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Role: Undiagnosed patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Role
  20220404183301349955_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Process: Medical diagnosis'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Process
  20220404183301349958_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Startdate
  20220404183301349961_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(date)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Enddate
  20220404183301349966_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Output type: Undiagnosed label'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Output
  20220404183301349969_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: Undiagnosed'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Attribute
  20220404183301349973_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: HP_Phenotype'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Input
  20220404183301349977_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hp_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Attribute
  20220404183301349980_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Input type: HGVS_Genotype'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genotype_Input
  20220404183301349983_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: 'Attribute type: $(hgvs_string)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(clinvar_uri)
  20220404183301349986_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220404183301349990_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Startdate
  20220404183301349994_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:date
        value: $(date)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Enddate
  20220404183301349998_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: Undiagnosed
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Undiagnosed_Output
  20220404183301350001_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(hp_label)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Phenotype_Input
  20220404183301350004_source_cde_test:
    predicateobject:
    - objects:
        datatype: xsd:string
        value: $(hgvs_string)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Genotype_Input
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

