mapping:
  20220607133255805368_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Treatment_role
      predicate: sio:SIO_000020
    - objects:
        type: iri
        value: sio:SIO_000115
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: $(pid)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_ID
  20220607133255805382_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Treatment_role
      predicate: sio:SIO_000228
    - objects:
        type: iri
        value: sio:SIO_000498
      predicate: rdf:type
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Entity
  20220607133255805390_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Drug_intake_process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Drug_prescription_process
      predicate: sio:SIO_000356
    - objects:
        type: iri
        value: sio:SIO_000016
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:OBI_0000093
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Role: Patient'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Treatment_role
  20220607133255805398_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Prescription_output
      predicate: sio:CHEMINF_000047
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Treatment_startdate
      predicate: sio:SIO_000680
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Treatment_enddate
      predicate: sio:SIO_000681
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Administration_input
      predicate: sio:SIO_000230
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Drug
      predicate: sio:SIO_000139
    - objects:
        type: iri
        value: obo:NCIT_C25538
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Drug intake'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Drug_intake_process
  20220607133255805402_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Prescription_output
      predicate: sio:SIO_000229
    - objects:
        type: iri
        value: obo:NCIT_C111077
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Process: Drug prescription'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Drug_prescription_process
  20220607133255805408_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Drug
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Dose
      predicate: sio:SIO_000628
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: obo:NCIT_C28180
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: Prescription
      predicate: rdfs:label
    - objects:
        datatype: xsd:string
        value: $(comments)
      predicate: rdfs:comment
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Prescription_output
  20220607133255805414_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Unit
      predicate: sio:SIO_000221
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Frequency
      predicate: sio:SIO_000900
    - objects:
        type: iri
        value: obo:NCIT_C25488
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: Dose
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Dose
  20220607133255805418_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: this:$(pid)_$(uniqid)_Drug
      predicate: sio:SIO_000313
    - objects:
        type: iri
        value: obo:NCIT_C177929
      predicate: rdf:type
    - objects:
        type: iri
        value: $(med_atc_type)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Drug component: $(med_atc_label)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: $(med_atc_uri)
  20220607133255805424_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000031
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Startdate: $(startdate)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(startdate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Treatment_startdate
  20220607133255805429_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000032
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Enddate: $(enddate)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:date
        value: $(enddate)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Treatment_enddate
  20220607133255805433_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_000015
      predicate: rdf:type
    - objects:
        type: iri
        value: $(routeURI)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Route of administration: $(routeLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Administration_input
  20220607133255805437_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(unitURI)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Unit: $(unitLabel)'
      predicate: rdfs:label
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Unit
  20220607133255805442_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: sio:SIO_010038
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: Drug
      predicate: rdfs:label
    - objects:
        datatype: xsd:float
        value: $(dose)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Drug
  20220607133255805447_source_cde_test:
    predicateobject:
    - objects:
        type: iri
        value: $(freqURI)
      predicate: rdf:type
    - objects:
        datatype: xsd:string
        value: 'Frequency: $(freqLabel)'
      predicate: rdfs:label
    - objects:
        datatype: xsd:integer
        value: $(freq)
      predicate: sio:SIO_000300
    sources:
    - source_cde_test
    subjects: this:$(pid)_$(uniqid)_Frequency
prefixes:
  obo: http://purl.obolibrary.org/obo/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sio: http://semanticscience.org/resource/
  this: '|||BASE|||'
  xsd: http://www.w3.org/2001/XMLSchema#
sources:
  source_cde_test:
    access: '|||DATA|||'
    iterator: $
    referenceFormulation: '|||FORMULATION|||'

