Birth_date:
  columns:
    pid: pat_id
    valueOutputDate: birthdate

Sex:
  columns:
    pid: pat_id
    valueAttributeIRI: sex_uri
    valueOutputString: sex

Care_pathway:
  columns:
    pid: pat_id
    valueOutputDate: first_visit_date

Diagnosis:
  columns:
    pid: pat_id
    valueAttributeIRI: diagnosis

Date_of_diagnosis:
  columns:
    pid: pat_id
    valueOutputDate: diagnosis_date
    valueAttributeIRI: onset_diagnosis

Onset_of_symptoms:
  columns:
    pid: pat_id
    valueAttributeIRI: onset_symptom
    valueOutputDate: first_symptoms_date

