Birth_date:
  columns:
    pid: pat_id
    valueOutput: birthdate
    startdate: observation
    enddate: observation

Sex:
  columns:
    pid: pat_id
    valueAttributeIRI: sex_uri
    valueOutput: sex
    startdate: observation
    enddate: observation

Patient_status:
  columns:
    pid: pat_id
    valueOutput: status_label
    valueAttributeIRI: status
    startdate: status_datetime
    enddate: status_datetime

Date_of_death:
  columns:
    pid: pat_id
    valueOutput: death_datetime
    startdate: death_datetime
    enddate: death_datetime

Care_pathway:
  columns:
    pid: pat_id
    valueOutput: first_visit_date
    startdate: first_visit_date
    enddate: first_visit_date

Diagnosis:
  columns:
    pid: pat_id
    valueAttributeIRI: diagnosis
    valueOutput: diagnosis_label
    startdate: diagnosis_date
    enddate: diagnosis_date

Date_of_diagnosis:
  columns:
    pid: pat_id
    valueOutput: diagnosis_date
    outputURI: onset_diagnosis
    startdate: diagnosis_date
    enddate: diagnosis_date

Onset_of_symptoms:
  columns:
    pid: pat_id
    outputURI: onset_symptom
    valueOutput: first_symptoms_date
    startdate: first_symptoms_date
    enddate: first_symptoms_date

Genotype:
  columns:
    pid: pat_id
    valueOutput: hgvs_string
    valueAttributeIRI: omim_code
    attributeURI: gen_id_type
    startdate: genetic_datetime
    enddate: genetic_datetime


Phenotype:
  columns:
    pid: pat_id
    valueAttributeIRI: dia_ce_sle_vasculitis_uri
    valueOutput: dia_ce_sle_vasculitis
    startdate: diagnosis_date
    enddate: diagnosis_date


Consent:
  columns:
    pid: pat_id
    valueOutput: consent_clinical
    outputURI: consent_clinical_uri
    startdate: informed_consent_date
    enddate: informed_consent_date


Disability:
  columns:
    pid: pat_id
    valueOutput: score
    processURI : disability_uri
    startdate: diagnosis_date
    enddate: diagnosis_date